import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import NextAuthProvider from "@/components/providers/NextauthProvider"
import { TanstackProvider } from "@/components/providers/TanstackProvider"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}): JSX.Element {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextAuthProvider>
                    <TanstackProvider>
                        {children}
                        <Toaster />
                    </TanstackProvider>
                </NextAuthProvider>
            </body>
        </html>
    )
}
